## Isaiah Wright notebook for Skills Assessment for the Research Analyst I position

## Report Questions
 • How many clients had 3 or more services in FY 2016-17?
 
 • What was the average amount of services per client in FY 2016-17?
 

• Create a chart that reflects the unique amount of clients who had jail services in FY 2016-17 broken down by Jail facility.  Note any findings.
 
 • Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name.  Note any findings.

• Note any other interesting findings from the data.

# Extracting the data from excel file


In [1]:
import pandas as pd

In [2]:
df = pd.read_excel (r'C:\Users\isaia\Downloads\Skills Assessment December 2020.xlsx', index_col=0, sheet_name=None)
print (df)

OrderedDict([('Instructions', Empty DataFrame
Columns: []
Index: [Answer as many of the below Report Questions in the "Report" tab that you can., Please show your work (formulas, pivot tables, etc.) and don’t be afraid to be creative with charts and graphs!, Create a dashboard using the program of your choice (Excel/PowerBi/Python/Etc..) to visually display your data., Compose a short narrative to explain your findings., Report Questions, • How many clients had 3 or more services in FY 2016-17?, • What was the average amount of services per client in FY 2016-17?, • Create a chart that reflects the unique amount of clients who had jail services in FY 2016-17 broken down by Jail facility.  Note any findings., • Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name.  Note any findings., • What percentage of unique clients that received IP Hospital services in FY 2016-17 were homeless?, • Note any other interesting findings fro

In [3]:
df_dict = {}
sheetname_list = ['Instructions', 'Clients', 'Client Services in FY 2016-17', 'Service Descriptions']
for sheet in sheetname_list:
    df_dict[sheet] = pd.read_excel(r'C:\Users\isaia\Downloads\Skills Assessment December 2020.xlsx', index_col=0, sheet_name=sheet)

In [4]:
df_dict

{'Instructions': Empty DataFrame
 Columns: []
 Index: [Answer as many of the below Report Questions in the "Report" tab that you can., Please show your work (formulas, pivot tables, etc.) and don’t be afraid to be creative with charts and graphs!, Create a dashboard using the program of your choice (Excel/PowerBi/Python/Etc..) to visually display your data., Compose a short narrative to explain your findings., Report Questions, • How many clients had 3 or more services in FY 2016-17?, • What was the average amount of services per client in FY 2016-17?, • Create a chart that reflects the unique amount of clients who had jail services in FY 2016-17 broken down by Jail facility.  Note any findings., • Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name.  Note any findings., • What percentage of unique clients that received IP Hospital services in FY 2016-17 were homeless?, • Note any other interesting findings from the data.

In [5]:
import numpy as np

In [6]:
df_dict['Client Services in FY 2016-17'] #checking to make sure I can access the various sheets through dictionary command

SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
Client ID                                                 
19               9502   2016-07-01         NaN         NaN
158              9503   2016-07-01         NaN         NaN
91               1141   2016-07-01         NaN         NaN
11               9507   2016-07-02         NaN         NaN
137              4131   2016-07-02         NaN         NaN
115              1522   2016-07-02         NaN         NaN
4                1211   2016-07-03         NaN         NaN
186              1211   2016-07-04         NaN         NaN
199              1531   2016-07-04         NaN         NaN
178              1522   2016-07-05         NaN         NaN
144              1541   2016-07-05         NaN         NaN
59               9501   2016-07-06         NaN        83.0
76               9503   2016-07-06         NaN         NaN
172              1511   2016-07-06         NaN         NaN
148              1211   2016-07-07         NaN         NaN
104              9502   2016-07-07         NaN         NaN
26               1141   2016-07-07         NaN         NaN
46               1522   2016-07-07         NaN         NaN
135              1541   2016-07-07         NaN         NaN
97               9505   2016-07-08         NaN         NaN
193              1511   2016-07-08         NaN         NaN
34               1511   2016-07-08         NaN         NaN
47               1522   2016-07-08         NaN         NaN
155              4131   2016-07-11         NaN         NaN
109              1211   2016-07-12         NaN         NaN
10               9502   2016-07-12         NaN         NaN
152              9503   2016-07-12         NaN         NaN
68               4131   2016-07-12         NaN         NaN
68               4132   2016-07-12         NaN         NaN
182              1211   2016-07-13         NaN         NaN
...               ...          ...         ...         ...
101              1541   2017-06-05         NaN         NaN
100              1211   2017-06-06         NaN         NaN
198              9504   2017-06-07         NaN         NaN
108              1511   2017-06-08         NaN         NaN
154              1511   2017-06-08         NaN         NaN
82               1541   2017-06-08         NaN         NaN
199              1541   2017-06-08         NaN         NaN
35               4131   2017-06-09         NaN         NaN
132              1211   2017-06-11         NaN         NaN
187              9503   2017-06-11         NaN         NaN
35               9505   2017-06-11         NaN         NaN
110              1511   2017-06-11         NaN         NaN
111              9502   2017-06-12         NaN         NaN
117              1511   2017-06-12         NaN         NaN
199              1141   2017-06-13         NaN         NaN
82               1141   2017-06-13         NaN         NaN
193              4132   2017-06-15         NaN         NaN
172              9502   2017-06-16         NaN         NaN
200              4131   2017-06-16         NaN         NaN
163              4131   2017-06-16         NaN         NaN
104              9503   2017-06-21         NaN         NaN
120              9503   2017-06-22         NaN         NaN
121              1541   2017-06-24         NaN         NaN
79               4131   2017-06-25         NaN         NaN
11               9508   2017-06-27         NaN         NaN
114              1522   2017-06-27         NaN         NaN
102              1522   2017-06-27         NaN         NaN
87               1541   2017-06-27         NaN         NaN
117              1511   2017-06-29         NaN         NaN
46               1541   2017-06-29         NaN         NaN

[514 rows x 4 columns]

In [7]:
df_dict['Instructions']

Empty DataFrame
Columns: []
Index: [Answer as many of the below Report Questions in the "Report" tab that you can., Please show your work (formulas, pivot tables, etc.) and don’t be afraid to be creative with charts and graphs!, Create a dashboard using the program of your choice (Excel/PowerBi/Python/Etc..) to visually display your data., Compose a short narrative to explain your findings., Report Questions, • How many clients had 3 or more services in FY 2016-17?, • What was the average amount of services per client in FY 2016-17?, • Create a chart that reflects the unique amount of clients who had jail services in FY 2016-17 broken down by Jail facility.  Note any findings., • Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name.  Note any findings., • What percentage of unique clients that received IP Hospital services in FY 2016-17 were homeless?, • Note any other interesting findings from the data., Term Definitions, IP Hospital - Psychiatric Inpatient Hospital, PERT - Psychiatric Emergency Response Team, Jail - Mental Health Services Received in a Jail Facility]

In [8]:
client = df_dict['Client Services in FY 2016-17'] #defining the client services sheet as a pandas dataframe for use

In [9]:
client

SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
Client ID                                                 
19               9502   2016-07-01         NaN         NaN
158              9503   2016-07-01         NaN         NaN
91               1141   2016-07-01         NaN         NaN
11               9507   2016-07-02         NaN         NaN
137              4131   2016-07-02         NaN         NaN
115              1522   2016-07-02         NaN         NaN
4                1211   2016-07-03         NaN         NaN
186              1211   2016-07-04         NaN         NaN
199              1531   2016-07-04         NaN         NaN
178              1522   2016-07-05         NaN         NaN
144              1541   2016-07-05         NaN         NaN
59               9501   2016-07-06         NaN        83.0
76               9503   2016-07-06         NaN         NaN
172              1511   2016-07-06         NaN         NaN
148              1211   2016-07-07         NaN         NaN
104              9502   2016-07-07         NaN         NaN
26               1141   2016-07-07         NaN         NaN
46               1522   2016-07-07         NaN         NaN
135              1541   2016-07-07         NaN         NaN
97               9505   2016-07-08         NaN         NaN
193              1511   2016-07-08         NaN         NaN
34               1511   2016-07-08         NaN         NaN
47               1522   2016-07-08         NaN         NaN
155              4131   2016-07-11         NaN         NaN
109              1211   2016-07-12         NaN         NaN
10               9502   2016-07-12         NaN         NaN
152              9503   2016-07-12         NaN         NaN
68               4131   2016-07-12         NaN         NaN
68               4132   2016-07-12         NaN         NaN
182              1211   2016-07-13         NaN         NaN
...               ...          ...         ...         ...
101              1541   2017-06-05         NaN         NaN
100              1211   2017-06-06         NaN         NaN
198              9504   2017-06-07         NaN         NaN
108              1511   2017-06-08         NaN         NaN
154              1511   2017-06-08         NaN         NaN
82               1541   2017-06-08         NaN         NaN
199              1541   2017-06-08         NaN         NaN
35               4131   2017-06-09         NaN         NaN
132              1211   2017-06-11         NaN         NaN
187              9503   2017-06-11         NaN         NaN
35               9505   2017-06-11         NaN         NaN
110              1511   2017-06-11         NaN         NaN
111              9502   2017-06-12         NaN         NaN
117              1511   2017-06-12         NaN         NaN
199              1141   2017-06-13         NaN         NaN
82               1141   2017-06-13         NaN         NaN
193              4132   2017-06-15         NaN         NaN
172              9502   2017-06-16         NaN         NaN
200              4131   2017-06-16         NaN         NaN
163              4131   2017-06-16         NaN         NaN
104              9503   2017-06-21         NaN         NaN
120              9503   2017-06-22         NaN         NaN
121              1541   2017-06-24         NaN         NaN
79               4131   2017-06-25         NaN         NaN
11               9508   2017-06-27         NaN         NaN
114              1522   2017-06-27         NaN         NaN
102              1522   2017-06-27         NaN         NaN
87               1541   2017-06-27         NaN         NaN
117              1511   2017-06-29         NaN         NaN
46               1541   2017-06-29         NaN         NaN

[514 rows x 4 columns]

In [10]:
client= client.reset_index() #creating a new index so that I can use the CLient ID variable

In [11]:
client

Client ID  SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
0           19        9502   2016-07-01         NaN         NaN
1          158        9503   2016-07-01         NaN         NaN
2           91        1141   2016-07-01         NaN         NaN
3           11        9507   2016-07-02         NaN         NaN
4          137        4131   2016-07-02         NaN         NaN
5          115        1522   2016-07-02         NaN         NaN
6            4        1211   2016-07-03         NaN         NaN
7          186        1211   2016-07-04         NaN         NaN
8          199        1531   2016-07-04         NaN         NaN
9          178        1522   2016-07-05         NaN         NaN
10         144        1541   2016-07-05         NaN         NaN
11          59        9501   2016-07-06         NaN        83.0
12          76        9503   2016-07-06         NaN         NaN
13         172        1511   2016-07-06         NaN         NaN
14         148        1211   2016-07-07         NaN         NaN
15         104        9502   2016-07-07         NaN         NaN
16          26        1141   2016-07-07         NaN         NaN
17          46        1522   2016-07-07         NaN         NaN
18         135        1541   2016-07-07         NaN         NaN
19          97        9505   2016-07-08         NaN         NaN
20         193        1511   2016-07-08         NaN         NaN
21          34        1511   2016-07-08         NaN         NaN
22          47        1522   2016-07-08         NaN         NaN
23         155        4131   2016-07-11         NaN         NaN
24         109        1211   2016-07-12         NaN         NaN
25          10        9502   2016-07-12         NaN         NaN
26         152        9503   2016-07-12         NaN         NaN
27          68        4131   2016-07-12         NaN         NaN
28          68        4132   2016-07-12         NaN         NaN
29         182        1211   2016-07-13         NaN         NaN
..         ...         ...          ...         ...         ...
484        101        1541   2017-06-05         NaN         NaN
485        100        1211   2017-06-06         NaN         NaN
486        198        9504   2017-06-07         NaN         NaN
487        108        1511   2017-06-08         NaN         NaN
488        154        1511   2017-06-08         NaN         NaN
489         82        1541   2017-06-08         NaN         NaN
490        199        1541   2017-06-08         NaN         NaN
491         35        4131   2017-06-09         NaN         NaN
492        132        1211   2017-06-11         NaN         NaN
493        187        9503   2017-06-11         NaN         NaN
494         35        9505   2017-06-11         NaN         NaN
495        110        1511   2017-06-11         NaN         NaN
496        111        9502   2017-06-12         NaN         NaN
497        117        1511   2017-06-12         NaN         NaN
498        199        1141   2017-06-13         NaN         NaN
499         82        1141   2017-06-13         NaN         NaN
500        193        4132   2017-06-15         NaN         NaN
501        172        9502   2017-06-16         NaN         NaN
502        200        4131   2017-06-16         NaN         NaN
503        163        4131   2017-06-16         NaN         NaN
504        104        9503   2017-06-21         NaN         NaN
505        120        9503   2017-06-22         NaN         NaN
506        121        1541   2017-06-24         NaN         NaN
507         79        4131   2017-06-25         NaN         NaN
508         11        9508   2017-06-27         NaN         NaN
509        114        1522   2017-06-27         NaN         NaN
510        102        1522   2017-06-27         NaN         NaN
511         87        1541   2017-06-27         NaN         NaN
512        117        1511   2017-06-29         NaN         NaN
513         46        1541   2017-06-29         NaN         NaN

[514 rows x 5 columns]

In [12]:

client.groupby('Client ID').size() #I need to be able to print this, the people have occur more than 3 times


Client ID
1       4
2       1
3       4
4       2
5       1
6       1
7       6
8       1
9       3
10     12
11     10
12      2
13      1
14      3
15      1
16      1
17      1
18      1
19      2
20      2
21      1
22      1
23      3
24      1
25      3
26      1
27      1
28      1
29      3
30      3
       ..
171     1
172    13
173     1
174     3
175     1
176     2
177     2
178     4
179     1
180     1
181     1
182     3
183     3
184     3
185     6
186     7
187    10
188     7
189     2
190     1
191     1
192     1
193     2
194     4
195     1
196     1
197     3
198     1
199    10
200     3
Length: 200, dtype: int64

In [13]:
client['Client ID']=client['Client ID'].astype(str) #converting Client ID to a string or object so that I can manipulate it


In [14]:
client.head

<bound method NDFrame.head of     Client ID  SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
0          19        9502   2016-07-01         NaN         NaN
1         158        9503   2016-07-01         NaN         NaN
2          91        1141   2016-07-01         NaN         NaN
3          11        9507   2016-07-02         NaN         NaN
4         137        4131   2016-07-02         NaN         NaN
5         115        1522   2016-07-02         NaN         NaN
6           4        1211   2016-07-03         NaN         NaN
7         186        1211   2016-07-04         NaN         NaN
8         199        1531   2016-07-04         NaN         NaN
9         178        1522   2016-07-05         NaN         NaN
10        144        1541   2016-07-05         NaN         NaN
11         59        9501   2016-07-06         NaN        83.0
12         76        9503   2016-07-06         NaN         NaN
13        172        1511   2016-07-06         NaN         NaN
14        148        1211

In [15]:
client['Client ID'].dtype #checking data type

dtype('O')

## Addressing questions 1 and 2 from the instructions

In [16]:
S=client['Client ID'].value_counts() #counting how many occurences each patient has 
S

104    15
172    13
10     12
11     10
199    10
187    10
41      9
143     9
68      9
100     8
111     8
34      7
186     7
188     7
130     6
46      6
185     6
7       6
88      6
82      6
120     6
85      5
45      5
157     5
162     5
101     5
122     5
125     4
87      4
170     4
       ..
136     1
56      1
155     1
190     1
119     1
26      1
99      1
95      1
31      1
28      1
49      1
66      1
17      1
50      1
175     1
180     1
63      1
166     1
165     1
142     1
39      1
108     1
98      1
103     1
135     1
92      1
6       1
192     1
65      1
112     1
Name: Client ID, Length: 200, dtype: int64

# Question 1 answer


In [17]:
print (S[S>2]) #identifying those who went for a service 3 or more times, found to be 66 out of 200 patients who had services 3 or more

104    15
172    13
10     12
11     10
199    10
187    10
41      9
143     9
68      9
100     8
111     8
34      7
186     7
188     7
130     6
46      6
185     6
7       6
88      6
82      6
120     6
85      5
45      5
157     5
162     5
101     5
122     5
125     4
87      4
170     4
       ..
151     4
194     4
74      4
47      4
163     4
1       4
9       3
30      3
73      3
86      3
91      3
72      3
14      3
70      3
139     3
118     3
184     3
144     3
25      3
159     3
23      3
197     3
174     3
182     3
200     3
29      3
123     3
156     3
84      3
183     3
Name: Client ID, Length: 66, dtype: int64


Since there are 66 of 200 patients who have gone more than 3 times we can conclude that the majority of patients only seek services between 0-2 times. This is further supported by the section below that indicates the mean value of services is 2.57. A little bit over a 3rd of the patients seek services 3 or more times, I would be curious to observe how many of these individuals are homeless versus are not, as well as which hospitals these patients belong to. This could help identify groups that need more help, or hospitals that may require additional funding due to additional workload. 

# Question 2 answer

In [18]:
S.mean() #identifying the mean value count or average number of times a patient used services

2.57

In [19]:
S.median() #median can be a better identifyier because it isn't as susceptible to outliers such as Client 104 who went 15 times.

2.0

This information would indicate that on average patients used services between 2 and 2.57 times. This could be an important observation because it indicates how frequently we can expect patients to seek out services. 

## Preparing to address instruction 3 for creating a chart that reflects the unique amount of clients who had jail services in FY 2016-2017 by jail facility

 Make a list of Subunit ID's and filter by the list 

In [20]:
subid_list = ['1141', '1511', '1512', '1521', '1522', '1531', '1541'] #create a sublist based on the jail facility codes in subunit


client['SubUnit ID'].isin(subid_list)
#extract this by unique Client Id
new = client['SubUnit ID'].isin(subid_list) #create a new variable, True if present in those jail facilities, False if not present


In [21]:
new

0      False
1      False
2       True
3      False
4      False
5       True
6      False
7      False
8       True
9       True
10      True
11     False
12     False
13      True
14     False
15     False
16      True
17      True
18      True
19     False
20      True
21      True
22      True
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
484     True
485    False
486    False
487     True
488     True
489     True
490     True
491    False
492    False
493    False
494    False
495     True
496    False
497     True
498     True
499     True
500    False
501    False
502    False
503    False
504    False
505    False
506     True
507    False
508    False
509     True
510     True
511     True
512     True
513     True
Name: SubUnit ID, Length: 514, dtype: bool

In [22]:
newframe=client[new] #Clients who had jail services
newframe

Client ID  SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
2          91        1141   2016-07-01         NaN         NaN
5         115        1522   2016-07-02         NaN         NaN
8         199        1531   2016-07-04         NaN         NaN
9         178        1522   2016-07-05         NaN         NaN
10        144        1541   2016-07-05         NaN         NaN
13        172        1511   2016-07-06         NaN         NaN
16         26        1141   2016-07-07         NaN         NaN
17         46        1522   2016-07-07         NaN         NaN
18        135        1541   2016-07-07         NaN         NaN
20        193        1511   2016-07-08         NaN         NaN
21         34        1511   2016-07-08         NaN         NaN
22         47        1522   2016-07-08         NaN         NaN
35         34        1512   2016-07-16         NaN         NaN
37         23        1511   2016-07-19         NaN         NaN
43        160        1522   2016-07-20         NaN         NaN
44         23        1512   2016-07-21         NaN         NaN
45        176        1541   2016-07-21         NaN         NaN
47        143        1541   2016-07-22         NaN         NaN
48         68        1522   2016-07-23         NaN         NaN
52        122        1522   2016-07-25         NaN         NaN
56        178        1541   2016-07-26         NaN         NaN
58         72        1541   2016-07-27         NaN         NaN
65        128        1141   2016-07-29         NaN         NaN
69         91        1141   2016-08-01         NaN         NaN
70         23        1512   2016-08-01         NaN         NaN
71        186        1522   2016-08-02         NaN         NaN
72         72        1541   2016-08-02         NaN         NaN
76        199        1522   2016-08-05         NaN         NaN
77        129        1522   2016-08-05         NaN         NaN
82        130        1511   2016-08-09         NaN         NaN
..        ...         ...          ...         ...         ...
457       183        1541   2017-05-19         NaN         NaN
458       134        1541   2017-05-19         NaN         NaN
463        12        1522   2017-05-22         NaN         NaN
464       101        1541   2017-05-22         NaN         NaN
468        77        1141   2017-05-25         NaN         NaN
469        58        1541   2017-05-25         NaN         NaN
472       172        1511   2017-05-27         NaN         NaN
473        25        1541   2017-05-28         NaN         NaN
474       125        1511   2017-05-30         NaN         NaN
475        41        1511   2017-05-31         NaN         NaN
478       151        1522   2017-06-01         NaN         NaN
479       200        1521   2017-06-02         NaN         NaN
480       184        1522   2017-06-02         NaN         NaN
482       131        1511   2017-06-03         NaN         NaN
483       104        1522   2017-06-04         NaN         NaN
484       101        1541   2017-06-05         NaN         NaN
487       108        1511   2017-06-08         NaN         NaN
488       154        1511   2017-06-08         NaN         NaN
489        82        1541   2017-06-08         NaN         NaN
490       199        1541   2017-06-08         NaN         NaN
495       110        1511   2017-06-11         NaN         NaN
497       117        1511   2017-06-12         NaN         NaN
498       199        1141   2017-06-13         NaN         NaN
499        82        1141   2017-06-13         NaN         NaN
506       121        1541   2017-06-24         NaN         NaN
509       114        1522   2017-06-27         NaN         NaN
510       102        1522   2017-06-27         NaN         NaN
511        87        1541   2017-06-27         NaN         NaN
512       117        1511   2017-06-29         NaN         NaN
513        46        1541   2017-06-29         NaN         NaN

[228 rows x 5 columns]

In [23]:
newframe['SubUnit ID'].astype(str) #change this data type to an object/string

2      1141
5      1522
8      1531
9      1522
10     1541
13     1511
16     1141
17     1522
18     1541
20     1511
21     1511
22     1522
35     1512
37     1511
43     1522
44     1512
45     1541
47     1541
48     1522
52     1522
56     1541
58     1541
65     1141
69     1141
70     1512
71     1522
72     1541
76     1522
77     1522
82     1511
       ... 
457    1541
458    1541
463    1522
464    1541
468    1141
469    1541
472    1511
473    1541
474    1511
475    1511
478    1522
479    1521
480    1522
482    1511
483    1522
484    1541
487    1511
488    1511
489    1541
490    1541
495    1511
497    1511
498    1141
499    1141
506    1541
509    1522
510    1522
511    1541
512    1511
513    1541
Name: SubUnit ID, Length: 228, dtype: object

In [24]:
client[new].groupby('Client ID')
client[new]

Client ID  SubUnit ID Service Date  Unnamed: 3  Unnamed: 4
2          91        1141   2016-07-01         NaN         NaN
5         115        1522   2016-07-02         NaN         NaN
8         199        1531   2016-07-04         NaN         NaN
9         178        1522   2016-07-05         NaN         NaN
10        144        1541   2016-07-05         NaN         NaN
13        172        1511   2016-07-06         NaN         NaN
16         26        1141   2016-07-07         NaN         NaN
17         46        1522   2016-07-07         NaN         NaN
18        135        1541   2016-07-07         NaN         NaN
20        193        1511   2016-07-08         NaN         NaN
21         34        1511   2016-07-08         NaN         NaN
22         47        1522   2016-07-08         NaN         NaN
35         34        1512   2016-07-16         NaN         NaN
37         23        1511   2016-07-19         NaN         NaN
43        160        1522   2016-07-20         NaN         NaN
44         23        1512   2016-07-21         NaN         NaN
45        176        1541   2016-07-21         NaN         NaN
47        143        1541   2016-07-22         NaN         NaN
48         68        1522   2016-07-23         NaN         NaN
52        122        1522   2016-07-25         NaN         NaN
56        178        1541   2016-07-26         NaN         NaN
58         72        1541   2016-07-27         NaN         NaN
65        128        1141   2016-07-29         NaN         NaN
69         91        1141   2016-08-01         NaN         NaN
70         23        1512   2016-08-01         NaN         NaN
71        186        1522   2016-08-02         NaN         NaN
72         72        1541   2016-08-02         NaN         NaN
76        199        1522   2016-08-05         NaN         NaN
77        129        1522   2016-08-05         NaN         NaN
82        130        1511   2016-08-09         NaN         NaN
..        ...         ...          ...         ...         ...
457       183        1541   2017-05-19         NaN         NaN
458       134        1541   2017-05-19         NaN         NaN
463        12        1522   2017-05-22         NaN         NaN
464       101        1541   2017-05-22         NaN         NaN
468        77        1141   2017-05-25         NaN         NaN
469        58        1541   2017-05-25         NaN         NaN
472       172        1511   2017-05-27         NaN         NaN
473        25        1541   2017-05-28         NaN         NaN
474       125        1511   2017-05-30         NaN         NaN
475        41        1511   2017-05-31         NaN         NaN
478       151        1522   2017-06-01         NaN         NaN
479       200        1521   2017-06-02         NaN         NaN
480       184        1522   2017-06-02         NaN         NaN
482       131        1511   2017-06-03         NaN         NaN
483       104        1522   2017-06-04         NaN         NaN
484       101        1541   2017-06-05         NaN         NaN
487       108        1511   2017-06-08         NaN         NaN
488       154        1511   2017-06-08         NaN         NaN
489        82        1541   2017-06-08         NaN         NaN
490       199        1541   2017-06-08         NaN         NaN
495       110        1511   2017-06-11         NaN         NaN
497       117        1511   2017-06-12         NaN         NaN
498       199        1141   2017-06-13         NaN         NaN
499        82        1141   2017-06-13         NaN         NaN
506       121        1541   2017-06-24         NaN         NaN
509       114        1522   2017-06-27         NaN         NaN
510       102        1522   2017-06-27         NaN         NaN
511        87        1541   2017-06-27         NaN         NaN
512       117        1511   2017-06-29         NaN         NaN
513        46        1541   2017-06-29         NaN         NaN

[228 rows x 5 columns]

In [25]:
newframe['SubUnit ID'].dtype

dtype('int64')

In [26]:
newframe['counts']= newframe.groupby(['SubUnit ID'])['Client ID'].transform('count') #create a column that couts the unique clients per facility

C:\Users\isaia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [27]:
newframe

Client ID  SubUnit ID Service Date  Unnamed: 3  Unnamed: 4  counts
2          91        1141   2016-07-01         NaN         NaN      24
5         115        1522   2016-07-02         NaN         NaN      83
8         199        1531   2016-07-04         NaN         NaN      10
9         178        1522   2016-07-05         NaN         NaN      83
10        144        1541   2016-07-05         NaN         NaN      57
13        172        1511   2016-07-06         NaN         NaN      37
16         26        1141   2016-07-07         NaN         NaN      24
17         46        1522   2016-07-07         NaN         NaN      83
18        135        1541   2016-07-07         NaN         NaN      57
20        193        1511   2016-07-08         NaN         NaN      37
21         34        1511   2016-07-08         NaN         NaN      37
22         47        1522   2016-07-08         NaN         NaN      83
35         34        1512   2016-07-16         NaN         NaN      11
37         23        1511   2016-07-19         NaN         NaN      37
43        160        1522   2016-07-20         NaN         NaN      83
44         23        1512   2016-07-21         NaN         NaN      11
45        176        1541   2016-07-21         NaN         NaN      57
47        143        1541   2016-07-22         NaN         NaN      57
48         68        1522   2016-07-23         NaN         NaN      83
52        122        1522   2016-07-25         NaN         NaN      83
56        178        1541   2016-07-26         NaN         NaN      57
58         72        1541   2016-07-27         NaN         NaN      57
65        128        1141   2016-07-29         NaN         NaN      24
69         91        1141   2016-08-01         NaN         NaN      24
70         23        1512   2016-08-01         NaN         NaN      11
71        186        1522   2016-08-02         NaN         NaN      83
72         72        1541   2016-08-02         NaN         NaN      57
76        199        1522   2016-08-05         NaN         NaN      83
77        129        1522   2016-08-05         NaN         NaN      83
82        130        1511   2016-08-09         NaN         NaN      37
..        ...         ...          ...         ...         ...     ...
457       183        1541   2017-05-19         NaN         NaN      57
458       134        1541   2017-05-19         NaN         NaN      57
463        12        1522   2017-05-22         NaN         NaN      83
464       101        1541   2017-05-22         NaN         NaN      57
468        77        1141   2017-05-25         NaN         NaN      24
469        58        1541   2017-05-25         NaN         NaN      57
472       172        1511   2017-05-27         NaN         NaN      37
473        25        1541   2017-05-28         NaN         NaN      57
474       125        1511   2017-05-30         NaN         NaN      37
475        41        1511   2017-05-31         NaN         NaN      37
478       151        1522   2017-06-01         NaN         NaN      83
479       200        1521   2017-06-02         NaN         NaN       6
480       184        1522   2017-06-02         NaN         NaN      83
482       131        1511   2017-06-03         NaN         NaN      37
483       104        1522   2017-06-04         NaN         NaN      83
484       101        1541   2017-06-05         NaN         NaN      57
487       108        1511   2017-06-08         NaN         NaN      37
488       154        1511   2017-06-08         NaN         NaN      37
489        82        1541   2017-06-08         NaN         NaN      57
490       199        1541   2017-06-08         NaN         NaN      57
495       110        1511   2017-06-11         NaN         NaN      37
497       117        1511   2017-06-12         NaN         NaN      37
498       199        1141   2017-06-13         NaN         NaN      24
499        82        1141   2017-06-13         NaN         NaN      24
506       121        1541   

In [28]:
counts2=client[new]['Client ID'].value_counts() #number of services used by client ID for each client
counts2

143    9
41     8
199    7
34     7
82     6
130    5
46     5
162    5
186    5
1      4
85     4
151    4
68     4
122    4
178    4
47     4
144    3
174    3
72     3
101    3
70     3
129    3
23     3
91     3
30     3
118    3
25     3
87     3
183    3
197    3
      ..
109    1
53     1
92     1
6      1
105    1
194    1
167    1
185    1
65     1
190    1
108    1
158    1
135    1
114    1
56     1
170    1
160    1
66     1
200    1
195    1
103    1
7      1
12     1
184    1
193    1
61     1
19     1
20     1
24     1
133    1
Name: Client ID, Length: 108, dtype: int64

# Creating a visual to show subunit ID as X, and number of occurences for each SubUnit as Y in order to show unique number of clients

In [29]:
ax = newframe['SubUnit ID'].value_counts().plot(kind='bar',
                                    figsize=(14,8),
                                    title="Number of unique amount of clients who had jail services in 16/17 by jail facility")
ax.set_xlabel("SubUnit for prisons")
ax.set_ylabel("Unique Number of Clients")

Text(0, 0.5, 'Unique Number of Clients')

Important to note that 1522 or Central Jail had the most unique amount of clients who had services at 83, while 1521 had the least with 6. Central jails are 1522, 1541, 1521, and 1141 while Eastern are 1511, and 1512. The Vista facility is 1531 located in the North coastal area. It would appear that the majority of clients are from the Central jails, perhaps indicating need for further study practices implemented by these jails. 

## Preparing to address Question 4. Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name. Note any findings.

In [30]:
df_dict['Instructions']

Empty DataFrame
Columns: []
Index: [Answer as many of the below Report Questions in the "Report" tab that you can., Please show your work (formulas, pivot tables, etc.) and don’t be afraid to be creative with charts and graphs!, Create a dashboard using the program of your choice (Excel/PowerBi/Python/Etc..) to visually display your data., Compose a short narrative to explain your findings., Report Questions, • How many clients had 3 or more services in FY 2016-17?, • What was the average amount of services per client in FY 2016-17?, • Create a chart that reflects the unique amount of clients who had jail services in FY 2016-17 broken down by Jail facility.  Note any findings., • Create a table that reflects the number of IP Hospital services in FY 2016-17 broken down by month and hospital name.  Note any findings., • What percentage of unique clients that received IP Hospital services in FY 2016-17 were homeless?, • Note any other interesting findings from the data., Term Definitions, IP Hospital - Psychiatric Inpatient Hospital, PERT - Psychiatric Emergency Response Team, Jail - Mental Health Services Received in a Jail Facility]

In [31]:
SD=df_dict['Service Descriptions']

In [32]:
C=df_dict['Client Services in FY 2016-17']

# This time I am going to need a dataframe that has not only the information from the Client services sheet, but also add both facility name and service category, this can likely be accomplished through a merge and creating on a new dataframe

In [35]:
S.update(C)

In [36]:
dict3

{'Service Facility Name': SubUnit ID
 1211         CO SD CO PSYCH HOSP INPAT
 9501               ALVARADO PKWY INST 
 9502               PH BAYVIEW HOSPITAL
 9503           PH PARADISE VALLEY HOSP
 9504               UCSD MEDICAL CENTER
 9505              SHARP GROSSMONT HOSP
 9506          SCRIPPS MERCY HEALTHCARE
 9507            PALOMAR MEDICAL CENTER
 9508                 TRI-CITY HOSPITAL
 9511         SHARP MESA VISTA HOSP (A)
 9515          OUT OF COUNTY HOSP ADULT
 4131                     CRF PERT MHSA
 4132                    CRF PERT STAFF
 1141           CO Adult Forensics Eval
 1511                 CO Las Colinas OP
 1512           CO Las Colinas IP (PSU)
 1521          CO Central Jail IP (PSU)
 1522                CO Central Jail OP
 1531    CO Vista Detention Facility OP
 1541     CO George Bailey Detention OP
 Name: Service Facility Name, dtype: object, 'Service Category': SubUnit ID
 1211    IP Hospital
 9501    IP Hospital
 9502    IP Hospital
 9503    IP Hospital
 95

# The best way to accomplish the last two task would be to create one giant dataframe with all of the information for homelessness as well as the services description information added. This would have to be done by joining and merging the sheets, although I have had multiple issues doing this. After that creating a table based on the IP hospitals broken down by month and hospital would be pretty simple, just making a visualization like the part above. Ideally I would create two visuals one breaking down services by hospital and another services by month. Then I would try and understand which hospitals had the largest number of unique clients and which were considered the busy months. I could also make a visual combining these two aspects showing the number of unique clients by month by location. All of this information would help inform which locations get the most services and when are high points where labor would have to be increased. 

# Similarly identifying homeless would be possible with the master file, using the same code to identify the breakdown of services by hospital I could break down the unique number of homeless by hospital and then create a code that took the number of homeless by location/ number of homless total. The reason this would be an important observation is because this would be an apples to apples comparison of which hospitals provided services to homeless the most. Another possible observation would be to compare homeless by Total clients per hospital. This would allow us to view the percentage of total clients that were homeless by hospital. This observation could lead to further investigation such as is this a high homeless area? Are there incentives for homeless to seek services at this location? 